### ISSUE TITLE
normalized_data shape

### ISSUE THREAD

**Issue by epyx25** [sadighian/crypto-rl#21]
In **[data_pipeline](https://github.com/sadighian/crypto-rl/blob/arctic-streaming-ticks-full/gym_trading/utils/data_pipeline.py#L238)** after concatenating

```python
            print(f'imbalance_data after apply_ema: {imbalance_data.shape}') # (86400, 21)
            print(f'normalized_data: {normalized_data.shape}') # (86400, 124)
            normalized_data = pd.concat((normalized_data, imbalance_data), axis=1) 
            print(f'normalized_data + imbalance_data: {normalized_data.shape}') # (172800, 145)
```
At the end `normalized_data.shape` should not be (86400, 145)? It seems, that the indices of `normalized_data` are timestamps (2020-06-19 23:58:38.964857+00:00, 2020-06-19 23:58:39.964857+00:00, 2020-06-19 23:58:40.964857+00:00), but `imbalance_data` has normal indices (85841, 85842, 85843) and concatenating the two data frames adds the rows with a lot of `NaN`'s, like in this [example](https://repl.it/repls/FractalSvelteKeyboardmapping#main.py).

```python
import pandas as pd

d1 = {'col1': [1, 2], 'col2': [3, 4]}
d2 = {'col3': [1, 2], 'col4': [3, 4]}
indices = ['A', 'B']
df1 = pd.DataFrame(data=d1, index=indices)
df2 = pd.DataFrame(data=d2)

df3 = pd.concat((df1, df2), axis=1)
print(df3)
```
```
   col1  col2  col3  col4
A   1.0   3.0   NaN   NaN
B   2.0   4.0   NaN   NaN
0   NaN   NaN   1.0   3.0
1   NaN   NaN   2.0   4.0
```

This could work:

`normalized_data = pd.concat((normalized_data, imbalance_data.set_index(normalized_data.index)), axis=1)`

Earlier I had problems with `NaN`s but I simple ignored it with

`observation[np.isnan(observation)] = 0`

in [_get_step_observation](https://github.com/sadighian/crypto-rl/blob/arctic-streaming-ticks-full/gym_trading/envs/base_environment.py#L508)

And one more question: 
To the LOB imbalances you add the [mean](https://github.com/sadighian/crypto-rl/blob/arctic-streaming-ticks-full/gym_trading/utils/data_pipeline.py#L168)  but in your paper there is no mention of it. Is it necessary?

**Comment by sadighian** [comment]
Hi @epyx25 ,

**1. Merging bug**
You are correct that there is an error there, but it is actually due to _how_ the EMA-Smoother being applied to the feature set. I've fixed the bug in the latest commit ([e5a6ed339ce98ed8b47a5fdcd2390bf7cfb0d3e9](https://github.com/sadighian/crypto-rl/commit/e5a6ed339ce98ed8b47a5fdcd2390bf7cfb0d3e9)). 

The patch required adding the `index` parameter when converting the data back to a DataFrame from numpy array in `apply_ema_all_data()`:
https://github.com/sadighian/crypto-rl/blob/b821f0369dbe80207b698c066772071dc4f13915/indicators/ema.py#L110


Note that the `_get_notional_imbalance()` method sets the DataFrame index to datetime when called:
https://github.com/sadighian/crypto-rl/blob/b821f0369dbe80207b698c066772071dc4f13915/gym_trading/utils/data_pipeline.py#L163


**2. Extra features**
- The `mean` feature is not obligatory
